//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookingFlight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenBay()
        {
            this.VeMayBays = new HashSet<VeMayBay>();
        }
    
        public string MaCB { get; set; }
        public string MaSB_Di { get; set; }
        public string MaSB_Den { get; set; }
        public Nullable<System.DateTime> NgayGioDi { get; set; }
        public Nullable<System.DateTime> NgayGioDen { get; set; }
    
        public virtual SanBay SanBayDi { get; set; }
        public virtual SanBay SanBayDen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeMayBay> VeMayBays { get; set; }
    }
}
